### ISSUE TITLE
Shop - Show 'Selling'

### ISSUE THREAD

**Issue by pedrorgirardi** [Convex-Dev/convexity#109]
When a Listing is created, the Asset is transferred to the Shop, and it 'disappears' from the seller's NFTs.

We should still show the asset in the seller's NFTs screen, but add a type of 'for sale' mark.

It should be possible to navigate to the listing from the NFT screen.

**Comment by mikera** [comment]
It would be possible to keep the asset in the user's account, just create an open "offer" to the shop. 

Not sure this is an improvement - might cause a failure if a listing sticks around after the user has transferred or sold the asset elsewhere. But at least you could give a sensible error ("Asset is no longer for sale") and cancel the listing at that point.

**Comment by pedrorgirardi** [comment]
Do you think it's better to do this way instead of doing the work in the app? (There are things the app needs to handle in both options.)

**Comment by mikera** [comment]
Not sure. Probably best to keep it as it is right now (just an idea)
