### ISSUE TITLE
Select Account UI

### ISSUE THREAD

**Issue by mikera** [Convex-Dev/convexity#14]
UI to select a destination/target Account. 

This UI will be common in a few places in the app. Should parameterise so that e.g. a custom title like "Select Transfer Destination Account" can be provided.

May need to think about:

- Difference between Actor and User accounts?
- Blacklisted / whitelisted accounts?

**Comment by deepheap** [comment]
I think **Scan QR Code** and *Input Address ...* might be better in a separate tab, so **Recent** and **Contacts** has more space.

In **Recent**, if the Address is in the **Address Book**, it should show the name of the contact as well.

![Simulator Screen Shot - iPhone 12 Pro Max - 2020-12-08 at 17 44 22](https://user-images.githubusercontent.com/67358743/101473970-0efba480-397d-11eb-8916-d9b3f493a87f.png)
